<a href="https://colab.research.google.com/github/Sneha7012/DATA-SCIENCE/blob/main/program%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

Array from list: [1 2 3 4 5]


In [5]:
array_with_range = np.arange(10)
print("Array with range:", array_with_range)

Array with range: [0 1 2 3 4 5 6 7 8 9]


In [6]:
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones_array = np.ones((2, 5))
print("Array of ones:\n", ones_array)

Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
